import { CardTemplateConfig, TemplatePresetId } from '../types';

export const DEFAULT_TEMPLATE_CONFIG: CardTemplateConfig = {
  presetId: 'classic-moeys',
  orientation: 'portrait',

  // Card Dimensions & Custom Size (កំណត់ទំហំកាត)
  cardWidthMm: 92,
  cardHeightMm: 128,
  cardBorderRadiusMm: 3,

  // Colors & Theme
  primaryColor: '#0c4a6e', // sky-950
  secondaryColor: '#b45309', // amber-700
  accentColor: '#1e3a8a', // blue-900
  cardBgColor: '#ffffff',
  innerBorderType: 'single',
  innerBorderColor: '#075985', // sky-800
  watermarkOpacity: 0.04,
  watermarkType: 'school-logo',
  watermarkSize: 130,

  // Header & Positioning
  showHeader: true,
  showRoyalMotto: true,
  showMinistry: true,
  showDepartment: true,
  showSchoolName: true,
  headerStyle: 'gradient',
  headerBgColorStart: '#075985',
  headerBgColorEnd: '#1e3a8a',
  headerTextColor: '#fef08a', // amber-200
  headerTitleKhmer: 'ប័ណ្ណសម្គាល់ខ្លួនសិស្ស',
  headerSubtitleKhmer: '',
  headerOffsetY: 0,
  headerScale: 1,
  headerKingdomOffsetX: 0,
  headerKingdomOffsetY: 0,
  headerMottoOffsetX: 0,
  headerMottoOffsetY: 0,
  headerMinistryOffsetX: 0,
  headerMinistryOffsetY: 0,
  headerDepartmentOffsetX: 0,
  headerDepartmentOffsetY: 0,
  headerSchoolNameOffsetX: 0,
  headerSchoolNameOffsetY: 0,
  headerKingdomFontSize: 8.8,
  headerMottoFontSize: 7.6,
  headerMinistryFontSize: 7.5,
  headerDepartmentFontSize: 7.0,
  headerSchoolNameFontSize: 8.5,
  headerKingdomKhmer: '',
  headerMottoKhmer: '',
  headerMinistryKhmer: '',
  headerDepartmentKhmer: '',
  headerSchoolNameKhmer: '',
  logoPosition: 'left',
  logoSize: 'medium',
  logoOffsetX: 0,
  logoOffsetY: 0,
  logoScale: 1,

  // Title Banner & Text («ប័ណ្ណសម្គាល់ខ្លួនសិស្ស»)
  showTitleBanner: true,
  showTitleBannerBg: true,
  titleBannerBgColor: '#075985',
  titleBannerBgColorEnd: '#1e3a8a',
  titleBannerTextColor: '#fef08a',
  titleFontSize: 10,
  titleOffsetX: 0,
  titleOffsetY: 0,
  showSubtitle: true,
  subtitleFontSize: 7.6,
  subtitleOffsetX: 0,
  subtitleOffsetY: 0,

  // Layers & Z-Index Ordering
  stampPositionMode: 'footer',
  photoZIndex: 20,
  stampZIndex: 25,
  signatureZIndex: 22,
  qrZIndex: 20,
  titleZIndex: 15,
  infoZIndex: 15,
  headerZIndex: 15,
  watermarkZIndex: 0,

  // Field toggles, custom labels & Positioning (អក្សរ Info)
  infoOffsetX: 0,
  infoOffsetY: 0,
  infoFontSize: 10,
  infoLineSpacing: 1.45,
  infoLabelWidth: 27,
  infoGapY: 3.5,
  infoScale: 1.0,
  infoWidthPercent: 100,
  expandInfoToFullCard: false,
  infoLayoutMode: 'full-width',
  showStudentId: true,
  labelStudentId: 'អត្តលេខ ID',
  showFullName: true,
  labelFullName: 'គោត្តនាម-នាម',
  showLatinName: true,
  labelLatinName: 'អក្សរឡាតាំង',
  showGender: true,
  labelGender: 'ភេទ',
  showDob: true,
  labelDob: 'ថ្ងៃខែឆ្នាំកំណើត',
  showPob: true,
  labelPob: 'ទីកន្លែងកំណើត',
  pobPlacement: 'full-width', // តាមការស្នើសុំ៖ ដាក់លាតសន្ធឹងពេញទទឹងកាត
  pobSingleLine: true, // ដាក់តែមួយជួរ
  combineDobPob: false,
  labelDobPob: 'ថ្ងៃខែឆ្នាំកំណើត',
  showGradeClass: true,
  labelGradeClass: 'ថ្នាក់ទី', // បង្ហាញតែថ្នាក់ទី មិនបង្ហាញបន្ទប់ទេ
  showParents: true,
  labelFather: 'ឈ្មោះឪពុក',
  labelMother: 'ឈ្មោះម្ដាយ',
  showPhone: true,
  labelPhone: 'ទូរស័ព្ទ',
  showBloodType: false,
  labelBloodType: 'ក្រុមឈាម',
  showExpiryDate: false,
  labelExpiryDate: 'សុពលភាពដល់',

  // Photo & QR Code (រូបភាព & កូដ QR)
  photoPosition: 'right',
  photoShape: 'rect-3x4',
  photoBorderColor: '#9ca3af',
  showPhotoBadge: false, // មិនបង្ហាញស្លាក 3x4 លើរូបថតតាមសំណើ
  photoOffsetX: 0,
  photoOffsetY: 0,
  photoWidthMm: 24,
  photoHeightMm: 32,
  photoZoom: 1,
  showQrCode: true,
  qrPosition: 'below-photo',
  qrSize: 48,
  qrOffsetX: 0,
  qrOffsetY: 0,

  // Footer, Stamp & Signatures (ត្រា, ថ្ងៃខែ & ហត្ថលេខា)
  showFooter: true,
  showLunarDate: true,
  showSolarDate: true,
  dateOffsetX: 0,
  dateOffsetY: 0,
  dateFontSize: 6.4,
  showPrincipalTitle: true,
  principalTitleText: '',
  principalTitleOffsetX: 0,
  principalTitleOffsetY: 0,
  principalTitleFontSize: 7.3,
  showPrincipalName: true,
  principalNameText: '',
  principalNameOffsetX: 0,
  principalNameOffsetY: 0,
  principalNameFontSize: 7.6,
  showStamp: true,
  stampOpacity: 0.88,
  stampRotation: -6,
  stampSize: 64,
  stampOffsetX: 0,
  stampOffsetY: 0,
  showSignature: true,
  signatureOffsetX: 0,
  signatureOffsetY: 0,
  signatureScale: 1,
  showFooterContact: false, // មិនបង្ហាញទំនាក់ទំនង 095858545 លើកាតតាមសំណើ
  footerOffsetY: 0,

  // Backside
  backsideTitle: 'បទបញ្ជាផ្ទៃក្នុង & លក្ខខណ្ឌប្រើប្រាស់',
  backsideSubtitle: 'RULES & GUIDELINES FOR STUDENT ID CARD',
  backsideRules: [
    'សិស្សត្រូវពាក់ប័ណ្ណសម្គាល់ខ្លួននេះជាប់ជាប្រចាំ ពេលមានវត្តមានក្នុងបរិវេណវិទ្យាល័យ និងក្នុងម៉ោងសិក្សា។',
    'ប័ណ្ណនេះមានសុពលភាពសម្រាប់ប្រើប្រាស់ក្នុងរយៈពេលមួយឆ្នាំសិក្សា មិនអាចផ្ទេរឱ្យបុគ្គលដទៃប្រើប្រាស់ជំនួសបានឡើយ។',
    'ហាមឃាត់ដាច់ខាតការកែបន្លំ កោសលុប ឬផ្លាស់ប្តូររូបថត និងព័ត៌មានដែលបានបោះពុម្ពនៅលើប័ណ្ណនេះ។',
    'ករណីបាត់បង់ ឬខូចខាត សាមីខ្លួនត្រូវរាយការណ៍បន្ទាន់មកការិយាល័យរដ្ឋបាល និងកិច្ចការសិស្ស ដើម្បីស្នើសុំទុតិយតា។',
  ],
  showBacksideRules: true,
  showBacksideContact: true,
  showBacksideQr: true,
};

export interface TemplatePresetInfo {
  id: TemplatePresetId;
  nameKhmer: string;
  nameEn: string;
  description: string;
  badgeColor: string;
  previewBg: string;
  config: Partial<CardTemplateConfig>;
}

export const TEMPLATE_PRESETS: TemplatePresetInfo[] = [
  {
    id: 'kamrieng-official',
    nameKhmer: 'គំរូវិទ្យាល័យកំរៀង (100% Kamrieng Match)',
    nameEn: 'Kamrieng High School Official',
    description: 'ទម្រង់ត្រូវតាមគំរូជាក់ស្តែង ១០០%៖ QR នៅកៀនស្ដាំខាងលើ, ព័ត៌មានអក្សរខៀវ, រូបថតនៅបាតខាងឆ្វេង, ហត្ថលេខានៅបាតខាងស្តាំ។',
    badgeColor: 'bg-amber-600 text-white',
    previewBg: 'from-amber-600 to-blue-700',
    config: {
      ...DEFAULT_TEMPLATE_CONFIG,
      presetId: 'kamrieng-official',
      cardLayoutMode: 'kamrieng-official',
      primaryColor: '#0f172a',
      secondaryColor: '#b45309',
      accentColor: '#2563eb',
      cardBgColor: '#fbfcf8',
      innerBorderType: 'single',
      innerBorderColor: '#60a5fa',
      cardBorderRadiusMm: 3,
      watermarkOpacity: 0.05,
      // Header & Title
      showHeader: true,
      showTitleBanner: true,
      showTitleBannerBg: false,
      titleBannerTextColor: '#b45309',
      titleFontSize: 11,
      headerTitleKhmer: 'ប័ណ្ណសម្គាល់ខ្លួនសិស្ស',
      showSubtitle: true,
      headerSubtitleKhmer: 'ឆ្នាំសិក្សា ២០២៥-២០២៦',
      subtitleFontSize: 7.5,
      // QR & Photo Placement
      qrPosition: 'top-right',
      qrSize: 46,
      photoPosition: 'bottom-left',
      photoWidthMm: 27,
      photoHeightMm: 36,
      photoBorderColor: '#60a5fa',
      photoShape: 'rect-3x4',
      // Info colors & layout
      infoLayoutMode: 'full-width',
      infoFontSize: 8.8,
      infoValueColor: '#2563eb',
      // Footer & Principal
      showFooter: true,
      showLunarDate: true,
      showSolarDate: true,
      principalTitleText: 'នាយកវិទ្យាល័យ',
      principalNameTextColor: '#dc2626',
      stampPositionMode: 'footer',
      photoZIndex: 20,
      stampZIndex: 25,
    },
  },
  {
    id: 'classic-moeys',
    nameKhmer: 'ស្តង់ដារ ក្រសួងអប់រំ (MoEYS Classic)',
    nameEn: 'Classic MoEYS Standard',
    description: 'ទម្រង់ស្តង់ដារផ្លូវការរបស់ក្រសួងអប់រំ យុវជន និងកីឡា ពណ៌ខៀវទឹកប៊ិច និងមាស។',
    badgeColor: 'bg-sky-800 text-white',
    previewBg: 'from-sky-700 to-blue-900',
    config: {
      ...DEFAULT_TEMPLATE_CONFIG,
      presetId: 'classic-moeys',
      primaryColor: '#0c4a6e',
      secondaryColor: '#b45309',
      accentColor: '#1e3a8a',
      cardBgColor: '#ffffff',
      innerBorderType: 'single',
      innerBorderColor: '#0369a1',
      headerBgColorStart: '#075985',
      headerBgColorEnd: '#1e3a8a',
      headerTextColor: '#fef08a',
      photoShape: 'rect-3x4',
    },
  },
  {
    id: 'royal-navy',
    nameKhmer: 'រាជធានី-ភ្នំពេញ (Royal Navy & Gold)',
    nameEn: 'Royal Navy Prestige',
    description: 'រចនាបថប្រណិត ពណ៌ខៀវចាស់កងទ័ពជើងទឹក និងក្បូរក្បាច់មាស សម្រាប់វិទ្យាល័យធំៗ។',
    badgeColor: 'bg-blue-950 text-amber-200',
    previewBg: 'from-blue-950 to-indigo-950',
    config: {
      ...DEFAULT_TEMPLATE_CONFIG,
      presetId: 'royal-navy',
      primaryColor: '#1e3a8a',
      secondaryColor: '#d97706',
      accentColor: '#1e40af',
      cardBgColor: '#fafaf9',
      innerBorderType: 'double',
      innerBorderColor: '#1e3a8a',
      headerBgColorStart: '#1e3a8a',
      headerBgColorEnd: '#0f172a',
      headerTextColor: '#fef08a',
      headerStyle: 'gold-accent',
      photoShape: 'rect-3x4',
      watermarkOpacity: 0.05,
    },
  },
  {
    id: 'emerald-gold',
    nameKhmer: 'បៃតង សុជីវធម៌ (Emerald Green)',
    nameEn: 'Emerald Eco & Ethics',
    description: 'ពណ៌បៃតងត្បូងមរកត តំណាងឱ្យការលូតលាស់ សុជីវធម៌ និងបរិស្ថានស្អាត។',
    badgeColor: 'bg-emerald-800 text-emerald-100',
    previewBg: 'from-emerald-800 to-teal-950',
    config: {
      ...DEFAULT_TEMPLATE_CONFIG,
      presetId: 'emerald-gold',
      primaryColor: '#065f46',
      secondaryColor: '#b45309',
      accentColor: '#047857',
      cardBgColor: '#f0fdf4',
      innerBorderType: 'single',
      innerBorderColor: '#047857',
      headerBgColorStart: '#065f46',
      headerBgColorEnd: '#064e3b',
      headerTextColor: '#fef3c7',
      photoShape: 'rounded',
      photoBorderColor: '#047857',
    },
  },
  {
    id: 'crimson-ruby',
    nameKhmer: 'ក្រហម-មាស វប្បធម៌ (Ruby Crimson)',
    nameEn: 'Ruby Crimson & Gold',
    description: 'ពណ៌ក្រហមឈាមជ្រូក និងទឹកមាស បង្ហាញពីភាពក្លាហាន ការប្តេជ្ញាចិត្ត និងកិត្តិយស។',
    badgeColor: 'bg-rose-900 text-rose-100',
    previewBg: 'from-rose-900 to-red-950',
    config: {
      ...DEFAULT_TEMPLATE_CONFIG,
      presetId: 'crimson-ruby',
      primaryColor: '#881337',
      secondaryColor: '#ca8a04',
      accentColor: '#9f1239',
      cardBgColor: '#fff1f2',
      innerBorderType: 'double',
      innerBorderColor: '#9f1239',
      headerBgColorStart: '#881337',
      headerBgColorEnd: '#701a75',
      headerTextColor: '#fef9c3',
      photoShape: 'rect-3x4',
      photoBorderColor: '#be123c',
    },
  },
  {
    id: 'modern-stem',
    nameKhmer: 'បច្ចេកវិទ្យា ទំនើប (STEM Slate & Cyan)',
    nameEn: 'Modern STEM & Tech',
    description: 'រចនាបថយុគសម័យឌីជីថល ព័ណ៌ប្រផេះក្រម៉ៅ និងខៀវស៊ីយ៉ាន ជ្រុងមូលទាន់សម័យ។',
    badgeColor: 'bg-slate-900 text-cyan-300',
    previewBg: 'from-slate-900 to-cyan-950',
    config: {
      ...DEFAULT_TEMPLATE_CONFIG,
      presetId: 'modern-stem',
      primaryColor: '#0f172a',
      secondaryColor: '#0284c7',
      accentColor: '#0369a1',
      cardBgColor: '#f8fafc',
      innerBorderType: 'minimal',
      innerBorderColor: '#0284c7',
      headerBgColorStart: '#0f172a',
      headerBgColorEnd: '#1e293b',
      headerTextColor: '#38bdf8',
      headerStyle: 'solid',
      photoShape: 'rounded',
      photoBorderColor: '#0284c7',
      showPhotoBadge: false,
    },
  },
  {
    id: 'minimal-ivory',
    nameKhmer: 'សាមញ្ញ ឆើតឆាយ (Minimalist Ivory)',
    nameEn: 'Clean Minimal Ivory',
    description: 'កាតស្អាតប្លែកបែបសាមញ្ញ ផ្ទៃពណ៌សក្បុស/ភ្លុកដំរី បន្ទាត់ឆ្មារប្រណិត។',
    badgeColor: 'bg-stone-800 text-stone-200',
    previewBg: 'from-stone-800 to-neutral-900',
    config: {
      ...DEFAULT_TEMPLATE_CONFIG,
      presetId: 'minimal-ivory',
      primaryColor: '#27272a',
      secondaryColor: '#a16207',
      accentColor: '#3f3f46',
      cardBgColor: '#fefce8',
      innerBorderType: 'single',
      innerBorderColor: '#78716c',
      headerBgColorStart: '#27272a',
      headerBgColorEnd: '#3f3f46',
      headerTextColor: '#fef08a',
      headerStyle: 'gold-accent',
      photoShape: 'rect-3x4',
      photoBorderColor: '#a1a1aa',
      watermarkOpacity: 0.02,
    },
  },
];

export function getEffectiveTemplateConfig(template?: CardTemplateConfig | null): CardTemplateConfig {
  if (!template) {
    return {
      ...DEFAULT_TEMPLATE_CONFIG,
      showPhotoBadge: false,
      showFooterContact: false,
      infoLabelWidth: 27,
      infoGapY: 3.5,
      infoScale: 1.0,
      infoWidthPercent: 100,
      expandInfoToFullCard: false,
      infoLayoutMode: 'full-width',
      pobPlacement: 'full-width',
      pobSingleLine: true,
      combineDobPob: false,
      labelDobPob: 'ថ្ងៃខែឆ្នាំកំណើត',
      labelGradeClass: 'ថ្នាក់ទី',
    };
  }
  return {
    ...DEFAULT_TEMPLATE_CONFIG,
    ...template,
    showPhotoBadge: false, // មិនបង្ហាញ 3x4 លើរូបថតតាមសំណើ
    showFooterContact: typeof template.showFooterContact === 'boolean' ? template.showFooterContact : false,
    infoLabelWidth: (template.infoLabelWidth && template.infoLabelWidth > 40) ? 27 : (template.infoLabelWidth || 27),
    infoLayoutMode: template.infoLayoutMode || 'full-width',
    pobPlacement: template.pobPlacement || 'full-width',
    pobSingleLine: typeof template.pobSingleLine === 'boolean' ? template.pobSingleLine : true,
    combineDobPob: typeof template.combineDobPob === 'boolean' ? template.combineDobPob : false,
    labelDobPob: (!template.labelDobPob || template.labelDobPob === 'ថ្ងៃខែឆ្នាំ និងទីកន្លែងកំណើត') ? 'ថ្ងៃខែឆ្នាំកំណើត' : template.labelDobPob,
    labelGradeClass: (!template.labelGradeClass || template.labelGradeClass === 'ថ្នាក់ទី / បន្ទប់') ? 'ថ្នាក់ទី' : template.labelGradeClass,
  };
}
